name: 01 - Hello

on:
    push:
        branches: [main]

jobs:
    hello:
        runs-on: ubuntu-24.04
        steps:
            - name: Hello World
              run: echo "Hello, World!"

            - name: Ver fecha y hora
              run: date

            - name: Ver archivos en el directorio
              run: ls -la
